import Foundation

/// Describes the public gateway endpoint and the hidden backend server it manages.
public struct ManagedGatewayRouting: Equatable {
    public static let backendPortOffset: Int = 100
    public static let defaultModelAlias = "default"

    public let publicPort: Int
    public let backendPort: Int
    public let activePresetName: String
    public let activeModel: String
    public let backendConfig: ServerConfig

    public init(config: ServerConfig) {
        self.init(
            config: config,
            publicPort: config.port,
            backendPort: config.port + Self.backendPortOffset
        )
    }

    public init(config: ServerConfig, publicPort: Int, backendPort: Int) {
        self.publicPort = publicPort
        self.backendPort = backendPort
        activePresetName = config.name
        activeModel = config.model
        backendConfig = config.withPort(backendPort)
    }

    /// Recover managed routing from an adopted backend process using the current app network settings.
    public static func recovered(server: DiscoveredServer, presets: [ServerConfig], settings: AppSettings) -> ManagedGatewayRouting? {
        for preset in presets {
            let resolved = preset.withResolvedPythonPath().withPort(settings.serverPort)
            let routing = ManagedGatewayRouting(
                config: resolved,
                publicPort: settings.managedGatewayPort,
                backendPort: settings.managedGatewayBackendPort
            )
            guard routing.backendPort == server.port else { continue }
            guard server.serverType == resolved.serverType else { continue }
            guard server.model == resolved.model else { continue }
            return routing
        }
        return nil
    }

    /// Recover managed routing from an adopted backend process when it matches a known preset.
    public static func recovered(server: DiscoveredServer, presets: [ServerConfig]) -> ManagedGatewayRouting? {
        for preset in presets {
            let resolved = preset.withResolvedPythonPath()
            let routing = ManagedGatewayRouting(config: resolved)
            guard routing.backendPort == server.port else { continue }
            guard server.serverType == resolved.serverType else { continue }
            guard server.model == resolved.model else { continue }
            return routing
        }
        return nil
    }

    public var acceptedModelAliases: Set<String> {
        [Self.defaultModelAlias, activePresetName, activeModel]
    }
}

/// Lightweight in-memory representation of an inbound HTTP request handled by the gateway.
public struct GatewayHTTPRequest: Equatable {
    public let method: String
    public let path: String
    public let headers: [String: String]
    public let body: Data

    public init(method: String, path: String, headers: [String: String], body: Data) {
        self.method = method
        self.path = path
        self.headers = headers
        self.body = body
    }
}

/// Lightweight in-memory HTTP response generated by the gateway.
public struct GatewayHTTPResponse: Equatable {
    public let statusCode: Int
    public let headers: [String: String]
    public let body: Data

    public init(statusCode: Int, headers: [String: String], body: Data) {
        self.statusCode = statusCode
        self.headers = headers
        self.body = body
    }
}

/// Result of handling a gateway request.
public enum ManagedGatewayDecision: Equatable {
    case forward(GatewayHTTPRequest)
    case respond(GatewayHTTPResponse)
}

/// Pure request router for the managed gateway.
public struct ManagedGatewayRequestHandler {
    private let routing: ManagedGatewayRouting

    public init(routing: ManagedGatewayRouting) {
        self.routing = routing
    }

    public func handle(request: GatewayHTTPRequest) throws -> ManagedGatewayDecision {
        if request.method.uppercased() == "GET", request.path == "/v1/models" {
            return .respond(modelsResponse())
        }

        return .forward(try rewriteModelAlias(in: request))
    }

    private func rewriteModelAlias(in request: GatewayHTTPRequest) throws -> GatewayHTTPRequest {
        guard !request.body.isEmpty else { return request }

        let object = try? JSONSerialization.jsonObject(with: request.body)
        guard var json = object as? [String: Any] else { return request }
        guard let requestedModel = json["model"] as? String else { return request }
        guard routing.acceptedModelAliases.contains(requestedModel) else { return request }

        json["model"] = routing.activeModel
        let rewrittenBody = try JSONSerialization.data(withJSONObject: json)
        return GatewayHTTPRequest(
            method: request.method,
            path: request.path,
            headers: request.headers,
            body: rewrittenBody
        )
    }

    private func modelsResponse() -> GatewayHTTPResponse {
        let models = [ManagedGatewayRouting.defaultModelAlias].map { id in
            [
                "id": id,
                "object": "model",
                "created": 0,
                "owned_by": "mlx-manager",
            ] as [String: Any]
        }
        let payload: [String: Any] = [
            "object": "list",
            "data": models,
        ]
        let body = (try? JSONSerialization.data(withJSONObject: payload)) ?? Data("{}".utf8)
        return GatewayHTTPResponse(
            statusCode: 200,
            headers: ["Content-Type": "application/json"],
            body: body
        )
    }
}
